version: '1.0'
name: branch-pipeline
displayName: Clash
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - clash
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: cert
        certificate: eded8f10-4225-013c-224e-3684bbb49d7c
        tag: ${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter: {}
        notify: []
        strategy:
          retry: '0'
          timeout: 60
  - name: stage-a1f09e77
    displayName: 发布
    strategy: naturally
    trigger: auto
    executor:
      - lzHernando
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 0.0.0.1
        autoIncrement: true
        notify: []
        strategy:
          retry: '0'
